---
# tasks file for prometheus
- name: Install prometheus on Debian
  include: debian.yml
  when:
    ansible_os_family == "Debian"

- name: Install prometheus on RedHat
  include: redhat.yml
  when:
    ansible_os_family == "RedHat"
