---

- name: Creating service user
  user:
   name: prometheus
   shell: /bin/false

# Create the necessary directories for storing Prometheus files and data
# Create a directory in /etc for Prometheus' configuration files and a directory in /var/lib for its data

- name: Create Prometheus directories
  file:
   path: /etc/prometheus
   path: /var/lib/prometheus
   state: directory
   mode: 0755
   owner: prometheus
   group: prometheus

- name: Download Prometheus
  get_url:
   url: https://github.com/prometheus/prometheus/releases/download/v2.0.0/prometheus-2.0.0.linux-amd64.tar.gz
   dest: /opt

- name: Unarchive prometheus
  unarchive:
    src: /opt/prometheus-2.0.0.linux-amd64.tar.gz
    dest: /opt/
    remote_src: yes
  tags:
   - untar

- name: Copy binary files to /usr/local/bin
  copy:
    src: "{{ item }}"
    dest: /usr/local/bin/
    owner: prometheus
    group: prometheus
    mode: 0755
    remote_src: yes
  with_items:
    - /opt/prometheus-2.0.0.linux-amd64/prometheus
    - /opt/prometheus-2.0.0.linux-amd64/promtool
  tags: copy_binary

- name: Create console directory
  command: cp -r /opt/prometheus-2.0.0.linux-amd64/consoles /etc/prometheus
  tags: console_directory

- name: Create consile_libraries
  command: cp -r /opt/prometheus-2.0.0.linux-amd64/console_libraries /etc/prometheus
  tags: console_lib

- name: Change ownership
  file: 
    path: "{{ item }}"
    owner: prometheus
    group: prometheus
    recurse: yes
  with_items:
    -  /opt/prometheus/console_libraries
    -  /opt/prometheus/consoles 

- name: Configuring prometheus.yml
  template:
    src: prometheus.yml
    dest: /etc/prometheus/
    owner: prometheus
    group: prometheus
  tags: prom.yml

- name: Configuring prometheus.service
  template:
    src: prometheus.service
    dest: /etc/systemd/system/
    mode: 0755
  tags: prom.service

- name: Reload Daemon
  become: true
  systemd: daemon_reload=yes
  tags: reload_daemon
  remote_src: yes
  
- name: Start Prometheus service
  become: true
  service:
    name: prometheus.service
    state: started
  tags: prom.start
  remote_src: yes
