---

- name: Apache exporter Install
  import_tasks: install.yml
  tags:
    - install

- name: Apache exporter Configure
  import_tasks: config.yml
  tags:
    - configure

- name: Apache exporter Service
  import_tasks: service.yml
  tags:
    - service
