---

- name: Configuring service
  systemd:
    name: apache-exporter
    daemon_reload: yes

- name: enable service apache-exporter and ensure it is not masked
  systemd:
    name: apache-exporter
    enabled: yes
    masked: no

- name: Start apache-exporter service
  service:
    name: apache-exporter
    state: started
