---

- name: Add the user MongoDB_exporter
  user:
   name: MongoDB_exporter
   shell: /bin/bash

- name: Download URL
  become: true
  get_url:
   url: "https://github.com/dcu/mongodb_exporter/releases/download/v1.0.0/mongodb_exporter-linux-amd64"
   dest: /opt
   mode: 755

- name: Copy binary files to /usr/local/bin
  become: true
  command: cp -r /opt/mongodb_exporter-linux-amd64 /usr/local/bin
  remote_src: yes

- name: Chnaging ownership of MongoDB_exporter
  file:
   path: /usr/local/bin/mongodb_exporter-linux-amd64
   owner: MongoDB_exporter
   group: MongoDB_exporter
   mode: 755
