---
#Updating sources.list
  
  - name: APT Repository
    apt_repository:
      repo: deb https://packagecloud.io/grafana/stable/debian/ stretch main
      state: present

#Updating APT Repository
  - name: apt-get update
    apt:
      update_cache: yes
      cache_valid_time: 3600
    become: true

#Installing dependencies
  - name: Install dependencies
    apt: 
      name: "{{ item }}"
      state: present
    with_items:
      - fonts-dejavu-core      
      - fontconfig-config
      - libfontconfig1

  - name: Install Grafana
    apt:
      name: grafana
      state: latest
    become: true

  - name: Start grafana service
    service:
      name: grafana-server
      state: restarted
