---

- name: MongoDB exporter Install
  import_tasks: install.yml
  tags:
    - install

- name: MongoDB exporter Configure
  import_tasks: config.yml
  tags:
    - configure

- name: MongoDB exporter Service
  import_tasks: service.yml
  tags:
    - service
