---

- name: Configuring service
  systemd:
    name: mysql-exporter
    daemon_reload: yes

- name: enable service mysql-exporter and ensure it is not masked
  systemd:
    name: mysql-exporter
    enabled: yes
    masked: no

- name: Start mysql-exporter service
  service:
    name: mysql-exporter
    state: started
