---

- name: Configuring service
  systemd:
    name: nginx-vts-exporter
    daemon_reload: yes

- name: enable service node-exporter and ensure it is not masked
  systemd:
    name: nginx-vts-exporter
    enabled: yes
    masked: no

- name: Start nginx-vts-exporter service
  service:
    name: nginx-vts-exporter
    state: started
