---

- name: NODE_EXPORTER Install
  import_tasks: install.yml
  tags:
    - install

- name: NODE_EXPORTER Configure
  import_tasks: config.yml
  tags:
    - configure

- name: NODE_EXPORTER Service
  import_tasks: service.yml
  tags:
    - service
